collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07787325
color:
  saturation: 0.4688507
  brandStrength: 1
  lightness: 0.4162191
  brandColors:
    - '#FFFFFF'
    - '#0A090E'
    - '#E9A37F'
    - '#594E52'
    - '#B57559'
  rhythmicContrast: 0.5171858
layout_spectrum: 0.9736842
name: "Marylou's Hair Studio"
